version: "3.1"
services:
  mongodb:
    image: mongo:3.6
    restart: always
    volumes:
      - ./mongo/data:/data/db
      #WINDOWS
      #- mongo_db:/data/db:Z
  app:
    container_name: hminode
#    build: .
#    image: docker.ramp.eu/opil/opil.sw.hmi:latest
    image: hmi:test
    environment:
      - inituser=admin
      - initpw=admin
      - ocb_host=10.0.2.15
      - ocb_port=1026
      - ngsi_proxy_host=10.0.2.15
      - ngsi_proxy_port=3000
      - SESSION_SECRET=ChangeThisSecret
#      - link_btn_txt=Open an External System
#      - link_btn_url=https://www.vttresearch.com/
#      - task_mgmnt=BPO
    restart: always
    volumes:
      - ./public/uploads:/usr/src/app/public/uploads
      #WINDOWS
      #- node_dir:/usr/src/app/public/uploads:Z
    ports:
      - "80:8081"
    depends_on:
      - mongodb
    command: bash -c './wait-for mongodb:27017 -- node server.js'

#WINDOWS
#volumes:
#    mongo_db: 
#        external: true
#    node_dir: 
#        external: true
