version: "3"
services:
  mongodb:
    image: mongo:3.6
    restart: always
    volumes:
      - ./mongo/data:/data/db
      #WINDOWS
      #- mongo_db:/data/db:Z
  app:
    container_name: hminode
    #build: .
    image: l4ms/opil.sw.hmi:latest
    environment:
     - inituser=admin
     - initpw=admin
    restart: always
    volumes:
      - ./public/uploads:/usr/src/app/public/uploads
      #WINDOWS
      #- node_dir:/usr/src/app/public/uploads:Z                
    ports:
      - "80:8081"
    depends_on:
      - mongodb
    command: bash -c './wait-for mongodb:27017 -- node server.js'

#WINDOWS
#volumes:
#    mongo_db: 
#        external: true
#    node_dir: 
#        external: true
